<?php

declare(strict_types=1);

// Dashboard / chat (Blade text). Strings generated by JS live in js.php.
return [
    'study_prompt_label' => 'What are we studying today?',
    'subject_placeholder' => '— Choose the subject —',
    'no_ready_book_suffix' => '(no book ready)',
    'clear_chat' => '🗑️ Clear chat',
    'session_tokens' => 'Tokens for this session:',
    'no_ready_books' => 'You don\'t have any ready books yet. Go to <a href=":url" class="underline font-semibold">📕 Books</a> and upload a PDF: as soon as it\'s ready we can study it together.',
    'input_placeholder' => 'Type your question here…',
    'mic_aria' => 'Dictate your question',
    'send' => 'Send',
    'modal_cancel' => 'Cancel',
];
